// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppendSaveTransfer(arg1, arg2) {
  return window['go']['main']['App']['AppendSaveTransfer'](arg1, arg2);
}

export function FinishSaveTransfer(arg1) {
  return window['go']['main']['App']['FinishSaveTransfer'](arg1);
}

export function LoadSavedAssetDirectory() {
  return window['go']['main']['App']['LoadSavedAssetDirectory']();
}

export function SaveProject(arg1, arg2) {
  return window['go']['main']['App']['SaveProject'](arg1, arg2);
}

export function SelectAssetDirectory() {
  return window['go']['main']['App']['SelectAssetDirectory']();
}

export function StartSaveTransfer(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartSaveTransfer'](arg1, arg2, arg3);
}

export function Startup(arg1) {
  return window['go']['main']['App']['Startup'](arg1);
}
