// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {context} from '../models';

export function AppendSaveTransfer(arg1:string,arg2:string):Promise<void>;

export function FinishSaveTransfer(arg1:string):Promise<void>;

export function LoadSavedAssetDirectory():Promise<main.AssetPayload>;

export function SaveProject(arg1:string,arg2:string):Promise<string>;

export function SelectAssetDirectory():Promise<main.AssetPayload>;

export function StartSaveTransfer(arg1:string,arg2:string,arg3:string):Promise<string>;

export function Startup(arg1:context.Context):Promise<void>;
