// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAssets() {
  return window['go']['main']['AssetManager']['GetAssets']();
}

export function GetImageBase64(arg1) {
  return window['go']['main']['AssetManager']['GetImageBase64'](arg1);
}

export function SelectAssetFolder() {
  return window['go']['main']['AssetManager']['SelectAssetFolder']();
}

export function Startup(arg1) {
  return window['go']['main']['AssetManager']['Startup'](arg1);
}
