// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {context} from '../models';

export function GetAssets():Promise<Array<main.AssetFile>>;

export function GetImageBase64(arg1:string):Promise<string>;

export function SelectAssetFolder():Promise<Array<main.AssetFile>>;

export function Startup(arg1:context.Context):Promise<void>;
