// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAudio(arg1) {
  return window['go']['main']['VideoExporter']['AddAudio'](arg1);
}

export function AddFrame(arg1) {
  return window['go']['main']['VideoExporter']['AddFrame'](arg1);
}

export function FinishExport() {
  return window['go']['main']['VideoExporter']['FinishExport']();
}

export function SelectSaveLocation() {
  return window['go']['main']['VideoExporter']['SelectSaveLocation']();
}

export function StartExport(arg1, arg2) {
  return window['go']['main']['VideoExporter']['StartExport'](arg1, arg2);
}

export function Startup(arg1) {
  return window['go']['main']['VideoExporter']['Startup'](arg1);
}
