// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function AddAudio(arg1:string):Promise<void>;

export function AddFrame(arg1:string):Promise<void>;

export function FinishExport():Promise<void>;

export function SelectSaveLocation():Promise<string>;

export function StartExport(arg1:string,arg2:number):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
