<!-- 
  @component FileExportPanel
  The primary I/O, persistence, and level management UI[cite: 19].
  Allows users to save/load full `.uvtt-proj` workspaces, manage multi-floor 
  map catalogs, and dispatch exports tailored to specific VTT platforms 
  (Foundry, Roll20, Fantasy Grounds) or generic Universal VTT schemas[cite: 19].
-->
<script>
  import { mapStore } from "$lib/stores/mapStore.svelte.js";
  import { packageForPlatform } from "$lib/utils/exporters.js";
  import JSZip from "jszip";

  // --- SVELTE 5 REACTIVE BINDINGS ---[cite: 19]
  let catalog = $derived(mapStore.catalog);
  let activeMap = $derived(mapStore.activeMap);

  /** @type {boolean} Toggle for compiling all maps in the catalog into a single zip archive[cite: 19]. */
  let packageCompound = $state(false);

  /**
   * Intercepts file uploads from the "Load Project" hidden input[cite: 19].
   * Routes standard `.uvtt-proj` or `.zip` archives to the central store for unpacking[cite: 19].
   *
   * @param {Event} e - The HTML input change event[cite: 19].
   */
  function triggerFileImport(e) {
    const file = e.target.files[0];
    if (file) mapStore.loadProjectFromFile(file);
    // Reset the input so the exact same file can be re-imported later if needed[cite: 19]
    e.target.value = null;
  }

  /**
   * Dispatches the active map(s) to the platform-specific compiler[cite: 19].
   * Translates the generic UVTT schema into bespoke formats required by Foundry, Roll20, etc[cite: 19].
   *
   * @param {string} platform - The target VTT platform identifier ('foundry', 'roll20', 'fg')[cite: 19].
   */
  async function handlePlatformExport(platform) {
    if (packageCompound) {
      // --- COMPOUND ARCHIVE EXPORT (Multi-Level) ---[cite: 19]
      if (catalog.length === 0) return;

      alert(
        `Packaging ${catalog.length} map levels into a ${platform.toUpperCase()} ZIP archive...`,
      );

      try {
        const zip = new JSZip();

        // Inject a readme for the user explaining the contents[cite: 19]
        zip.file(
          "README_Export.txt",
          `Compound Dungeon Export for ${platform.toUpperCase()}\nGenerated by UVTT v2 IDE\nContains ${catalog.length} map level(s).`,
        );

        // Compile each map level individually and inject into the ZIP archive[cite: 19]
        for (let i = 0; i < catalog.length; i++) {
          const mapDef = catalog[i];
          const { filename, data } = await packageForPlatform(
            platform,
            mapDef.manifest,
          );
          // Prepend the floor index to ensure chronological ordering in the OS file explorer[cite: 19]
          const safeFilename = `Floor_${i + 1}_${filename}`;
          zip.file(safeFilename, data);
        }

        const zipBlob = await zip.generateAsync({ type: "blob" });
        mapStore.downloadBlob(
          `Compound_Dungeon_${platform.toUpperCase()}_Export.zip`,
          zipBlob,
        );
      } catch (err) {
        console.error("ZIP Generation Failed:", err);
        alert(`Compound Export to ${platform} failed: ${err.message}`);
      }
    } else {
      // --- SINGLE MAP EXPORT ---[cite: 19]
      if (!activeMap) return;
      try {
        const { filename, data } = await packageForPlatform(
          platform,
          activeMap.manifest,
        );
        mapStore.downloadBlob(
          filename,
          new Blob([data], { type: "application/json" }),
        );
      } catch (err) {
        alert(`Export to ${platform} failed: ${err.message}`);
      }
    }
  }
</script>

<div class="panel-section">
  <h3>💾 FILE & EXPORT</h3>

  <label class="checkbox-row" style="margin-bottom: 8px;">
    <input type="checkbox" bind:checked={packageCompound} />
    <span>Package Catalog as Compound Dungeon</span>
  </label>

  <div style="display: flex; gap: 8px; flex-direction: column;">
    <!-- PROJECT I/O CONTROLS -->
    <div style="display: flex; gap: 8px;">
      <button
        class="action-btn wave"
        style="flex: 1; justify-content: center;"
        onclick={() => mapStore.saveProject()}
      >
        📦 Save
      </button>
      <button
        class="action-btn"
        style="flex: 1; justify-content: center; background: #ef444422; border-color: #ef4444; color: #fca5a5;"
        onclick={() => {
          if (
            confirm(
              "Close project and return to start screen? Unsaved changes will be lost.",
            )
          )
            mapStore.closeProject();
        }}
      >
        ❌ Close
      </button>
    </div>

    <!-- MAP CATALOG (LEVEL MANAGEMENT) -->
    <div
      class="panel-section"
      style="border-color: rgba(168, 85, 247, 0.4); background: rgba(168, 85, 247, 0.02); margin-top: 12px; padding: 10px;"
    >
      <h3 style="color: #a855f7;">🗺️ MAP LEVELS</h3>
      <div style="display: flex; flex-direction: column; gap: 8px;">
        {#each catalog as level}
          <div
            style="display: flex; gap: 4px; align-items: center; width: 100%; min-width: 0;"
          >
            <!-- Map Switcher Button[cite: 19] -->
            <button
              class="action-btn {mapStore.activeMapId === level.id
                ? 'wave'
                : ''}"
              title={level.filename}
              style="flex: 1; min-width: 0; overflow: hidden; white-space: nowrap; text-overflow: ellipsis; text-align: left; padding-right: 8px; display: block; border-color: {mapStore.activeMapId ===
              level.id
                ? '#a855f7'
                : '#334155'}; color: {mapStore.activeMapId === level.id
                ? '#a855f7'
                : '#94a3b8'};"
              onclick={() => mapStore.switchMap(level.id)}
            >
              {level.filename}
            </button>

            <!-- Contextual Actions (Only show for the currently active map)[cite: 19] -->
            {#if mapStore.activeMapId === level.id}
              <button
                class="action-btn"
                style="padding: 4px 8px; flex-shrink: 0;"
                title="Rename Level"
                onclick={() => {
                  const newName = prompt("Rename map level:", level.filename);
                  if (newName) mapStore.renameMapLevel(level.id, newName);
                }}>✏️</button
              >

              <button
                class="action-btn"
                style="padding: 4px 8px; color: #ef4444; border-color: rgba(239,68,68,0.3); flex-shrink: 0;"
                title="Delete Level"
                onclick={() => {
                  if (confirm("Delete this level entirely?"))
                    mapStore.deleteMapLevel(level.id);
                }}>🗑️</button
              >
            {/if}
          </div>
        {/each}

        <button
          class="action-btn"
          style="justify-content: center; margin-top: 4px; border-style: dashed;"
          onclick={() => mapStore.addMapLevel()}
        >
          ➕ Add Blank Level
        </button>
      </div>
    </div>

    <!-- LOAD PROJECT TRIGGER -->
    <label
      class="action-btn"
      style="background: #1e293b; color: #e2e8f0; text-align: center; cursor: pointer; justify-content: center;"
    >
      📂 Load Project
      <input
        type="file"
        accept=".uvtt-proj,.zip"
        style="display: none;"
        onchange={triggerFileImport}
      />
    </label>

    <!-- UNIVERSAL VTT EXPORTERS -->
    <div style="display: flex; gap: 8px;">
      <button
        class="action-btn"
        onclick={() =>
          packageCompound
            ? mapStore.exportCompoundVTT(true)
            : mapStore.exportLegacyV1()}
      >
        ⏳ Export v1
      </button>
      <button
        class="action-btn positive"
        onclick={() =>
          packageCompound
            ? mapStore.exportCompoundVTT(false)
            : mapStore.exportVTT()}
      >
        📤 Compile v2
      </button>
    </div>

    <button
      class="action-btn secure"
      onclick={() => mapStore.exportSecureVTT(packageCompound)}
    >
      🔒 Secure Archive (.zip)
    </button>
  </div>

  <!-- PLATFORM SPECIFIC COMPILERS -->
  <div
    style="margin-top: 12px; border-top: 1px solid #1e293b; padding-top: 10px;"
  >
    <h4 style="color: #64748b; font-size: 10px; margin-bottom: 8px;">
      PLATFORM EXPORTS
    </h4>
    <div style="display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 4px;">
      <button class="action-btn" onclick={() => handlePlatformExport("foundry")}
        >Foundry</button
      >
      <button class="action-btn" onclick={() => handlePlatformExport("roll20")}
        >Roll20</button
      >
      <button class="action-btn" onclick={() => handlePlatformExport("fg")}
        >FG</button
      >
    </div>
  </div>

  <p class="helper-text" style="margin-top: 5px;">
    Your work is continuously auto-saved to your browser's local cache.
  </p>
</div>

<style>
  .panel-section {
    display: flex;
    flex-direction: column;
    gap: 10px;
    border-bottom: 1px solid #1e293b;
    padding-bottom: 10px;
    margin-bottom: 10px;
  }
  .checkbox-row {
    display: flex;
    flex-direction: row;
    align-items: center;
    gap: 8px;
    margin-top: 5px;
    cursor: pointer;
    font-size: 12px;
    color: #94a3b8;
  }
  input[type="checkbox"] {
    cursor: pointer;
    width: 14px;
    height: 14px;
    accent-color: #00f0ff;
  }
  h3 {
    margin: 0;
    font-size: 14px;
    color: #00f0ff;
    text-transform: uppercase;
  }
  h4 {
    margin: 0;
    font-size: 12px;
  }
  .helper-text {
    font-size: 11px;
    color: #94a3b8;
    line-height: 1.4;
  }
  button {
    background: #1e293b;
    border: 1px solid #334155;
    color: #e2e8f0;
    padding: 8px 10px;
    border-radius: 6px;
    cursor: pointer;
    font-weight: 500;
    display: flex;
    justify-content: flex-start;
    align-items: center;
    gap: 8px;
    transition: all 0.2s;
    font-size: 13px;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
  }
  button:hover {
    background: #334155;
  }
  .action-btn {
    flex: 1;
    font-size: 12px;
    padding: 8px;
    justify-content: center;
  }
  .action-btn.positive {
    background: #ef444422;
    border-color: #ef4444;
    color: #fca5a5;
  }
  .action-btn.wave {
    background: #3b82f622;
    border-color: #3b82f6;
    color: #93c5fd;
  }
  .action-btn.secure {
    background: #a855f722;
    border-color: #a855f7;
    color: #d8b4fe;
  }
</style>
